export const estadosList = [
  { estado: "AC", estadoNome: "Acre" },
  { estado: "AL", estadoNome: "Alagoas" },
  { estado: "AP", estadoNome: "Amapá" },
  { estado: "AM", estadoNome: "Amazonas" },
  { estado: "BA", estadoNome: "Bahia" },
  { estado: "CE", estadoNome: "Ceará" },
  { estado: "DF", estadoNome: "Brasilia" },
  { estado: "ES", estadoNome: "Espirito Santo" },
  { estado: "GO", estadoNome: "Goias" },
  { estado: "MA", estadoNome: "Maranhão" },
  { estado: "MT", estadoNome: "Mato Grosso" },
  { estado: "MS", estadoNome: "Mato Grosso do Sul" },
  { estado: "MG", estadoNome: "Minas Gerais" },
  { estado: "PA", estadoNome: "Pará" },
  { estado: "PB", estadoNome: "Paraiba" },
  { estado: "PR", estadoNome: "Parana" },
  { estado: "PE", estadoNome: "Pernambuco" },
  { estado: "PI", estadoNome: "Piaui" },
  { estado: "RJ", estadoNome: "Rio de Janeiro" },
  { estado: "RN", estadoNome: "Rio Grande do Norte" },
  { estado: "RS", estadoNome: "Rio Grande do Sul" },
  { estado: "RO", estadoNome: "Rondonia" },
  { estado: "RR", estadoNome: "Roraima" },
  { estado: "SC", estadoNome: "Santa Catarina" },
  { estado: "SP", estadoNome: "São Paulo" },
  { estado: "SE", estadoNome: "Sergipe" },
  { estado: "TO", estadoNome: "Tocantins" },
];
